name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # CMake build type (Release, Debug, RelWithDebInfo)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.0'

      - name: Install Linux dependencies
        run: sudo apt-get install -y libudev-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH='${{env.Qt6_Dir}}/lib/cmake/' -B '${{github.workspace}}/build'

      - name: Build
        run: cmake --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}

      - name: Package
        run: cmake --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}} --target artefact

      - name: Upload Windows
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: robocut_windows
          path: ${{github.workspace}}/build/*-*.zip

      - name: Upload Mac
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: robocut_mac
          path: ${{github.workspace}}/build/*-*.dmg
