name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # CMake build type (Release, Debug, RelWithDebInfo)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.0'

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH='${{env.Qt6_Dir}}/lib/cmake/' -B '${{github.workspace}}/build'

      - name: Build
        run: cmake --build '${{github.workspace}}'/build
